#!/usr/bin/env bash
# Generates snapcraft.yaml by appending a part + component for every voice
# listed in voices.yaml to the static template in snapcraft.yaml.in.
#
# Usage:
#   ./generate_snapcraft.sh > snapcraft.yaml
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
template="${script_dir}/snapcraft.yaml.in"
voices_yaml="${script_dir}/voices.yaml"

cat <<'EOF'
# This file is generated by generate_snapcraft.sh from snapcraft.yaml.in and
# voices.yaml. Do not hand-edit the "parts" entries or "components" section
# below; edit snapcraft.yaml.in or voices.yaml and re-run generate_snapcraft.sh.
EOF
cat "$template"

components_yaml=""

mapfile -t locales < <(yq -r 'keys_unsorted[]' "$voices_yaml")

for locale in "${locales[@]}"; do
  language_raw="${locale%-*}"
  country_raw="${locale##*-}"
  language_lower="$(printf '%s' "$language_raw" | tr '[:upper:]' '[:lower:]')"
  country_lower="$(printf '%s' "$country_raw" | tr '[:upper:]' '[:lower:]')"
  country_upper="$(printf '%s' "$country_raw" | tr '[:lower:]' '[:upper:]')"
  locale_underscore="${language_lower}_${country_upper}"

  mapfile -t voice_ids < <(yq -r --arg locale "$locale" '.[$locale].voices[]' "$voices_yaml")

  for voice_id in "${voice_ids[@]}"; do
    name_lower="${voice_id%-*}"
    quality_lower="${voice_id##*-}"

    comp_name="voices-${language_lower}-${country_lower}-${name_lower}-${quality_lower}"
    dir_name="${locale_underscore}-${name_lower}-${quality_lower}"
    onnx_file="${dir_name}.onnx"
    base_url="https://huggingface.co/rhasspy/piper-voices/resolve/main/${language_lower}/${locale_underscore}/${name_lower}/${quality_lower}"

    cat <<EOF

  ${comp_name}:
    plugin: dump
    source: ./component-base
    build-packages:
      - curl
      - ca-certificates
    override-build: |
      craftctl default
      set -eu
      mkdir -p "\$CRAFT_PART_INSTALL/${dir_name}"
      curl -L --fail --retry 3 \\
        -o "\$CRAFT_PART_INSTALL/${dir_name}/${onnx_file}" \\
        "${base_url}/${onnx_file}"
      curl -L --fail --retry 3 \\
        -o "\$CRAFT_PART_INSTALL/${dir_name}/${onnx_file}.json" \\
        "${base_url}/${onnx_file}.json"
    organize:
      ${dir_name}/${onnx_file}: (component/${comp_name})/${onnx_file}
      ${dir_name}/${onnx_file}.json: (component/${comp_name})/${onnx_file}.json
      meta/hooks/install: (component/${comp_name})/meta/hooks/install
      meta/hooks/post-refresh: (component/${comp_name})/meta/hooks/post-refresh
EOF

    components_yaml+="
  ${comp_name}:
    type: standard
    summary: ${locale} ${name_lower} voice for Piper
    description: ${locale} ${name_lower} voice for Piper
    version: '0.1'
    hooks:
      install: {}
      post-refresh: {}
"
  done
done

printf '\ncomponents:%s' "$components_yaml"
